force-app/main/default/objects/ProductTeamMember__c/ProductTeamMember__c.object-meta.xml
<CustomObject>
    <label>Product Team Member</label>
    <nameField>
        <displayFormat>Member-{000000}</displayFormat>
        <label>PTM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductTeamMember__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Team Members</relationshipLabel>
    <relationshipName>Product_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/ProductAccessLevel__c.field-meta.xml
<CustomField>
    <fullName>ProductAccessLevel__c</fullName>
    <label>Product Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
                <default>true</default>
                <label>Read</label>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Full Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/utility/TestUtility.cls
/**
 * @description       : Contain reusable utility methods for test classes
**/
@isTest
public class TestUtility {

    private static final String PERMISSION_SET_NAME = 'Product_Team_Access';
    
    public static User buildUser(String profileName, String lastName, Boolean shouldInsert) {
        Profile p = [SELECT Id FROM Profile WHERE Name = :profileName];
        User u = new User(
            Alias = 'standt',
            Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8',
            LastName = lastName,
            LanguageLocaleKey ='en_US',
            LocaleSidKey ='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = Crypto.getRandomLong() + '@' + Crypto.getRandomLong() + '.abc',
            isActive = true
        );

        if (shouldInsert) {
            insert u;
            assignPermissionSet(u.Id);
        }

        return u;
    }

    public static ProductTeamMember__c buildProductTeamMember(Id productId, Id userId, String access, Boolean shouldInsert) {
        ProductTeamMember__c ptm = new ProductTeamMember__c(
            Name__c = 'Product Team Member Name Test',
            Product__c = productId,
            User__c = userId,
            ProductAccessLevel__c = access
        );

        if (shouldInsert) {
            insert ptm;
        }

        return ptm;
    }

    @future
    public static void assignPermissionSet(Id userId) {
        PermissionSet ps = [
            SELECT Id
            FROM PermissionSet
            WHERE Name = :PERMISSION_SET_NAME
        ];

        insert new PermissionSetAssignment(AssigneeId = userId, PermissionSetId = ps.Id);
    }
}