force-app/main/default/objects/Product_Team_Member_Type__mdt/Product_Team_Member_Type__mdt.object-meta.xml
<CustomObject>
    <description>CMDT holds the possible product team member types, which will be used for creating Product Team Member records</description>
    <label>Product Team Member Type</label>
    <pluralLabel>Product Team Member Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/IsSOQL__c.field-meta.xml
<CustomField>
    <fullName>IsSOQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSOQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/ObjectIcon__c.field-meta.xml
<CustomField>
    <fullName>ObjectIcon__c</fullName>
    <label>ObjectIcon</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/ObjectTypeLabel__c.field-meta.xml
<CustomField>
    <fullName>ObjectTypeLabel__c</fullName>
    <label>ObjectTypeLabel</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/QueryFields__c.field-meta.xml
<CustomField>
    <fullName>QueryFields__c</fullName>
    <label>QueryFields</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/SearchCondition__c.field-meta.xml
<CustomField>
    <fullName>SearchCondition__c</fullName>
    <label>SearchCondition</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/controllers/BaseLookupController.cls
/**
 * @description       : BaseLookupController
 **/
public with sharing class BaseLookupController {
    public static List<LookupSearchResult> search(
        String searchTerm,
        List<String> selectedIds,
        Product_Team_Member_Type__mdt controller
    ) {
        List<SObject> searchResults;
        if (controller.IsSOQL__c) {
            searchResults = LookupSearchUtility.performSOQLSearch(
                searchTerm,
                controller.ObjectType__c,
                controller.QueryFields__c,
                controller.SearchCondition__c
            );
        } else {
            searchResults = LookupSearchUtility.performSOSLSearch(
                searchTerm,
                controller.ObjectType__c,
                controller.QueryFields__c,
                selectedIds
            );
        }

        List<LookupSearchResult> results = new List<LookupSearchResult>();
        for (SObject obj : searchResults) {
            results.add(mapToLookupSearchResult(obj, controller));
        }
        results.sort();

        return results;
    }

    private static LookupSearchResult mapToLookupSearchResult(SObject obj, Product_Team_Member_Type__mdt controller) {
        String subtitle = controller.ObjectTypeLabel__c + ' • ' + (String) obj.get('Name');
        return new LookupSearchResult(
            obj.Id,
            controller.ObjectTypeLabel__c,
            controller.ObjectIcon__c,
            (String) obj.get('Name'),
            subtitle
        );
    }
}