force-app/main/default/objects/Product_Team_Member_Type__mdt/Product_Team_Member_Type__mdt.object-meta.xml
<CustomObject>
    <description>CMDT holds the possible product team member types, which will be used for creating Product Team Member records</description>
    <label>Product Team Member Type</label>
    <pluralLabel>Product Team Member Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product_Team_Member_Type__mdt/fields/MemberTypeLookupField__c.field-meta.xml
<CustomField>
    <fullName>MemberTypeLookupField__c</fullName>
    <label>MemberTypeLookupField</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/ProductTeamMember__c.object-meta.xml
<CustomObject>
    <label>Product Team Member</label>
    <nameField>
        <displayFormat>Member-{000000}</displayFormat>
        <label>PTM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductTeamMember__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/PermissionSet__c.field-meta.xml
<CustomField>
    <fullName>PermissionSet__c</fullName>
    <label>Permission Set</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Team Members</relationshipLabel>
    <relationshipName>Product_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/ProductAccessLevel__c.field-meta.xml
<CustomField>
    <fullName>ProductAccessLevel__c</fullName>
    <label>Product Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
                <default>true</default>
                <label>Read</label>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Full Access</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/PublicGroup__c.field-meta.xml
<CustomField>
    <fullName>PublicGroup__c</fullName>
    <label>Public Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/Queue__c.field-meta.xml
<CustomField>
    <fullName>Queue__c</fullName>
    <label>Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Define the sharing reason in a product.</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Permission Set</fullName>
            </value>
            <value>
                <fullName>Public Group</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
            <value>
                <fullName>Role</fullName>
            </value>
            <value>
                <fullName>Territory</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marketing Agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductTeamMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Product_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/controllers/ProductTeamMemberController.cls
/**
 * @description       : Controller class holds logic for :
 *  - Retrieving possible options for the product team member types
 *  - Search functionality depending on the selected product team member type
 *  - Product Team Member record creation
 **/
public with sharing class ProductTeamMemberController {
  private static final String PRODUCT_ACCESS_LEVEL = 'ProductAccessLevel';
  private static final String TEAM_MEMBER_ROLE = 'TeamMemberRole';
  private static final String USER_NAME = 'UserName';
  private static List<String> permissableAccesses = new List<String> { ProductAccessUtility.ACCESS_LEVELS.get('Full_Access') };
  private static final Map<String, String> REASON_MAPPING = new Map<String, String> {
    'Role__c' => 'Role',
    'PermissionSet__c' => 'Permission Set',
    'PublicGroup__c' => 'Public Group',
    'Queue__c' => 'Queue',
    'Territory__c' => 'Territory',
    'User__c' => 'User'
  };

  @AuraEnabled(cacheable=true)
  public static List<ProductTeamMemberType> getProductTeamMemberTypes() {
    List<ProductTeamMemberType> types = new List<ProductTeamMemberType>();
    for (Product_Team_Member_Type__mdt productTeamMemberType : [
      SELECT Label, DeveloperName, MemberTypeLookupField__c
      FROM Product_Team_Member_Type__mdt
    ]) {
      types.add(
        new ProductTeamMemberType(
          productTeamMemberType.Label,
          productTeamMemberType.DeveloperName,
          productTeamMemberType.MemberTypeLookupField__c
        )
      );
    }
    return types;
  }

  @AuraEnabled(cacheable=true scope='global')
  public static List<LookupSearchResult> search(
    String searchTerm,
    List<String> selectedIds,
    String productTeamMemberTypeName
  ) {
    try {
      Product_Team_Member_Type__mdt record = Product_Team_Member_Type__mdt.getInstance(
        productTeamMemberTypeName
      );
      return BaseLookupController.search(searchTerm, selectedIds, record);
    } catch (Exception e) {
      throw new AuraHandledException('error while searching ' + e.getMessage());
    }
  }

  @AuraEnabled
  public static String createProductTeamMember(
    String productId,
    String memberId,
    String accessLevel,
    String productTeamMemberLookupField,
    String productTeamMemberRole
  ) {
    try {
      ProductTeamMember__c productTeamMember = new ProductTeamMember__c();
      productTeamMember.Product__c = productId;
      productTeamMember.ProductAccessLevel__c = accessLevel;
      productTeamMember.TeamMemberRole__c = productTeamMemberRole;
      productTeamMember.Reason__c = REASON_MAPPING.get(
        productTeamMemberLookupField
      );
      productTeamMember.put(productTeamMemberLookupField, memberId);
      productTeamMember.Name__c = getRecordNameFromId(memberId);
      insert productTeamMember;
      return productTeamMember.Id;
    } catch (Exception e) {
      throw new AuraHandledException(
        'Failed to create product team member: ' + e.getMessage()
      );
    }
  }

  @AuraEnabled
  public static List<ProductTeamMemberAccessWrapper> fetchProductTeamMemberAccess(
    Id productId
  ) {
    Set<Id> productIds = new Set<Id>{ productId };
    Map<Id, List<ProductTeamMemberAccessWrapper>> productTeamMemberAccesses = ProductAccessUtility.fetchProductTeamMemberAccess(
      productIds
    );

    return productTeamMemberAccesses.get(productId);
  }

  private static String getRecordNameFromId(Id recordId) {
    String objectType = recordId.getSObjectType().getDescribe().getName();
    String fieldName = 'Name';

    if (fieldName != null) {
      String query =
        'SELECT ' +
        fieldName +
        ' FROM ' +
        objectType +
        ' WHERE Id = :recordId LIMIT 1';
      SObject result = Database.query(query);
      return (String) result.get(fieldName);
    }
    return null;
  }

  @AuraEnabled
  public static Boolean checkUserPermission(Id productId) {
    try {
      Id currentUserId = UserInfo.getUserId();
      Boolean hasGlobalPermission = ProductAccessUtility.hasModifyAllData(currentUserId);

      Product2 product = [SELECT Id, CreatedById FROM Product2 WHERE Id = :productId WITH USER_MODE LIMIT 1];
      
      Boolean hasAccess = (product.CreatedById == currentUserId) || hasGlobalPermission;

      if (!hasAccess) {
        Set<Id> productIds = new Set<Id> { productId };
        Map<Id, List<ProductTeamMemberAccessWrapper>> productsUserAccesses = ProductAccessUtility.fetchProductTeamMemberAccess(productIds, new List<Id> { currentUserId });
        List<ProductTeamMemberAccessWrapper> wrapperUserList = productsUserAccesses.get(productId);
        hasAccess = ProductAccessUtility.checkUserProductAccess(wrapperUserList, permissableAccesses);
      }

      return hasAccess;
    } catch(Exception e) {
      throw new AuraHandledException(
        'Error while checking access for user to manage product team member ' + e.getMessage()
      );
    }
  }

  public class ProductTeamMemberType {
    @AuraEnabled
    public String label { get; set; }
    @AuraEnabled
    public String value { get; set; }
    @AuraEnabled
    public String memberTypeLookupField { get; set; }

    public ProductTeamMemberType(
      String label,
      String value,
      String memberTypeLookupField
    ) {
      this.label = label;
      this.value = value;
      this.memberTypeLookupField = memberTypeLookupField;
    }
  }

  public class ProductTeamMemberAccess {
    @AuraEnabled
    public String name { get; set; }
    @AuraEnabled
    public String role { get; set; }
    @AuraEnabled
    public String access { get; set; }
    @AuraEnabled
    public String reason { get; set; }

    public ProductTeamMemberAccess(
      String name,
      String role,
      String access,
      String reason
    ) {
      this.name = name;
      this.role = role;
      this.access = access;
      this.reason = reason;
    }
  }
}